### ISSUE TITLE
Some of Response are not getting into 

### ISSUE THREAD

**Issue by argotri** [blibli-badak/selenium-har-util#11]
Response is not recorderd in HAR Files , 
Need to investigate it
![image](https://user-images.githubusercontent.com/5022171/206956143-c2b25ca8-5963-4f95-910f-54e757c2a2c1.png)

**Comment by argotri** [comment]
Reproduce able on the test in the package

**Comment by Piyush140899** [comment]
Hi I am facing the same issue can you please elaborate more on step 2. what is run test mvn clean verify exactly
