### ISSUE TITLE
Incorrect Timings 

### ISSUE THREAD

**Issue by Piyush140899** [blibli-badak/selenium-har-util#27]
Hi thanks for checking my timing error issue, I did update the version to 1.0.11 but still getting the same issue with time. I don't feel it was a chrome version issue as I was getting the same error when I was on chrome v15

![image](https://github.com/blibli-badak/selenium-har-util/assets/55733043/cad8af2c-ccd9-4617-82e5-bc48770aae96)

**Comment by argotri** [comment]
hi @Piyush140899 , thank you for reporting the issue , 

could you please elaborate more about chrome v15 ? because we already trying in the chrome 117 are working fine as expected , 

![image](https://github.com/blibli-badak/selenium-har-util/assets/5022171/137286a8-9ab8-4130-bf8d-a5357c619eda)

**Comment by argotri** [comment]
closing issue since no reply from the reporter , please reopen if the issue still happen
