### ISSUE TITLE
it seems only support english response?

### ISSUE THREAD

**Issue by qdyzw** [blibli-badak/selenium-har-util#51]
"CodeVerGroup": "pk202403",
                       "Desc": "é¨ç½²ç­ç¥ï¼æ§å¶æºå¨äººè¸¢è¶³çï¼è¿è¡5V5çç²¾å½©å¯¹å³",

i drop the har file to chrome dev tool,then i see some response data become mojibake , it only support english response data?

**Comment by MHabiib** [comment]
hi @qdyzw thank you for using our open source util,
for the above issue may i know what language that used for the "Desc"?

**Comment by qdyzw** [comment]
> hi @qdyzw thank you for using our open source util, for the above issue may i know what language that used for the "Desc"?

hi,it's simplified Chinese.
it's very useful tool

**Comment by argotri** [comment]
hi @qdyzw  may i know the sample of website that we can use ? might be there are some unicode issue in the util

**Comment by qdyzw** [comment]
> hi @qdyzw may i know the sample of website that we can use ? might be there are some unicode issue in the util

hello,you can use selenium to open website https://api.vvhan.com/hotlist.html,then check the message field.

the normal data:
{
  "success": false,
  "code": 88888,
  "message": "接口路径不存在 请前往  https://api.vvhan.com/  查看免费API接口列表"
}


our har util data:
{
  "success": false,
  "code": 88888,
  "message": "æ¥å£è·¯å¾ä¸å­å¨ è¯·åå¾  https://api.vvhan.com/  æ¥çåè´¹APIæ¥å£åè¡¨"
}

**Comment by MHabiib** [comment]
Hi @qdyzw,

Could you attach the HAR file? When I try this on my local setup, the issue is not occurring.

<img width="997" alt="image" src="https://github.com/blibli-badak/selenium-har-util/assets/42311916/c561d117-4327-4569-ae10-0f9e278bfea6">
I used https://toolbox.googleapps.com/apps/har_analyzer/, and it shows the following:

<img width="786" alt="image" src="https://github.com/blibli-badak/selenium-har-util/assets/42311916/b7b360e7-34ff-41cf-b049-fd9bd8ed07ea">
The response includes Unicode escape sequences.

**Comment by qdyzw** [comment]
> Hi @qdyzw,
> 
> Could you attach the HAR file? When I try this on my local setup, the issue is not occurring.
> 
> <img alt="image" width="997" src="https://private-user-images.githubusercontent.com/42311916/335460612-c561d117-4327-4569-ae10-0f9e278bfea6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzgxNDQsIm5iZiI6MTcxNzEzNzg0NCwicGF0aCI6Ii80MjMxMTkxNi8zMzU0NjA2MTItYzU2MWQxMTctNDMyNy00NTY5LWFlMTAtMGY5ZTI3OGJmZWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA2NDQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MGUzNzk3YTAyZDkzZWJlOGM0MDkxZjZiOGRhM2FjM2FiYjNiOTE4ZTk2ZmYzNDI2MDY0ZTRhNjg1YzdhMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dBTZ-xkAVKXlDFEwWTHhiS34-mk72JB42IDL5TcDvwU"> I used https://toolbox.googleapps.com/apps/har_analyzer/, and it shows the following: <img alt="image" width="786" src="https://private-user-images.githubusercontent.com/42311916/335460688-b7b360e7-34ff-41cf-b049-fd9bd8ed07ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzgxNDQsIm5iZiI6MTcxNzEzNzg0NCwicGF0aCI6Ii80MjMxMTkxNi8zMzU0NjA2ODgtYjdiMzYwZTctMzRmZi00MWNmLWIwNDktZmQ5YmQ4ZWQwN2VhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDA2NDQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYjFlNWVmNGQyZDYxNDJlZWFhNjkxZWUzYThlYzQ5OWIwMGNmNzg0YjlkZmE5MTFmMzk5NjY0Yzk1MzViYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fqS_HrS4pstoSe6w9up_qYBvHbNy1G2VbBdXuXWVpXw"> The response includes Unicode escape sequences.

ok
[ttt.zip](https://github.com/user-attachments/files/15509490/ttt.zip)

**Comment by MHabiib** [comment]
Hi @qdyzw,

Thanks for attaching the HAR file. From my review, there doesn't seem to be an issue on the HAR side. The problem might be on your side while decoding the Unicode to Simplified Chinese.
Here is a sample code snippet if you are using Java:

String decodedStr = new String(originalStr.getBytes(StandardCharsets.ISO_8859_1), StandardCharsets.UTF_8);

**Comment by qdyzw** [comment]
> Hi @qdyzw,
> 
> Thanks for attaching the HAR file. From my review, there doesn't seem to be an issue on the HAR side. The problem might be on your side while decoding the Unicode to Simplified Chinese. Here is a sample code snippet if you are using Java:
> 
> String decodedStr = new String(originalStr.getBytes(StandardCharsets.ISO_8859_1), StandardCharsets.UTF_8);

![image](https://github.com/blibli-badak/selenium-har-util/assets/59500480/c0465ca3-053b-4b94-8416-20cd29d5a7ef)
i copy this unicode to gpt,it can decode the right language,but if i just drop the file to chrome or firefox ,it just become mojibake,then i find some website to decode that unicode,it become mojibake too,it confuse me.....
![image](https://github.com/blibli-badak/selenium-har-util/assets/59500480/bec874c0-2775-47b0-bca9-18eceeebb2f1)

anyway,thank you !

**Comment by argotri** [comment]
able to reproduce and already found the solution, there will be added support for setting up charset in the next release ( 1.3.0 ) waiting for review the code

**Comment by argotri** [comment]
https://github.com/blibli-badak/selenium-har-util/releases/tag/1.3.0
done, released , sorry for long time , because i just came back from my vacation
